"""UX package (English-only UI, see CLAUDE.md section 0): guards against
Cyrillic creeping back into user-facing strings. Comments/docstrings and test
fixtures are exempt (CLAUDE.md 0.7/0.8) — only string literals in production
code are checked.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

CYRILLIC = re.compile(r"[Ѐ-ӿ]")

ROOT = Path(__file__).resolve().parent.parent

PYTHON_ROOTS = ["abkit", "backend", "cli.py", "cli_admin.py", "migrations"]
PYTHON_EXCLUDE_DIRS = {"__pycache__", "tests"}
# Legacy Russian values matched (not displayed) by a one-off data migration
# that relabels pre-existing DB rows to the new English defaults (CLAUDE.md
# 0.4) — these are data being matched, not UI text.
PYTHON_EXCLUDE_FILES = {"0004_english_default_block_titles.py"}

TS_ROOT = ROOT / "frontend" / "src"
TS_EXCLUDE_FILES = {"schema.ts"}  # generated by openapi-typescript from backend descriptions

LINE_COMMENT_RE = re.compile(r"//.*$", re.MULTILINE)
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)


def _python_files() -> list[Path]:
    files = []
    for root in PYTHON_ROOTS:
        path = ROOT / root
        if path.is_file():
            files.append(path)
        elif path.is_dir():
            for p in path.rglob("*.py"):
                if p.name in PYTHON_EXCLUDE_FILES:
                    continue
                if not any(part in PYTHON_EXCLUDE_DIRS for part in p.relative_to(ROOT).parts):
                    files.append(p)
    return files


def _docstring_ids(tree: ast.AST) -> set[int]:
    # Any bare string-literal expression statement is documentation, not
    # runtime data — this covers both real docstrings (first statement of a
    # module/class/function) and the "attribute docstring" convention used
    # throughout abkit's dataclasses/Pydantic models (a string literal right
    # after a field, e.g. abkit/config.py, abkit/experiment.py).
    ids = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            ids.add(id(node.value))
    return ids


def test_no_cyrillic_in_python_ui_strings():
    offenders: list[str] = []
    for path in _python_files():
        src = path.read_text(encoding="utf-8")
        try:
            tree = ast.parse(src, filename=str(path))
        except SyntaxError:
            continue
        docstring_ids = _docstring_ids(tree)
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                if id(node) in docstring_ids:
                    continue
                if CYRILLIC.search(node.value):
                    offenders.append(f"{path.relative_to(ROOT)}:{node.lineno}: {node.value[:60]!r}")

    assert not offenders, "Cyrillic found in production Python string literals:\n" + "\n".join(offenders)


def test_no_cyrillic_in_frontend_ui_strings():
    offenders: list[str] = []
    for path in TS_ROOT.rglob("*.ts*"):
        if path.name in TS_EXCLUDE_FILES:
            continue
        src = path.read_text(encoding="utf-8")
        stripped = BLOCK_COMMENT_RE.sub("", LINE_COMMENT_RE.sub("", src))
        for lineno, line in enumerate(stripped.splitlines(), start=1):
            if CYRILLIC.search(line):
                offenders.append(f"{path.relative_to(ROOT)}:{lineno}: {line.strip()[:80]!r}")

    assert not offenders, "Cyrillic found in frontend UI code (outside comments):\n" + "\n".join(offenders)
