/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_v1_experiments__name__get"];
        put?: never;
        post?: never;
        /** Delete Experiment */
        delete: operations["delete_experiment_api_v1_experiments__name__delete"];
        options?: never;
        head?: never;
        /** Patch Experiment */
        patch: operations["patch_experiment_api_v1_experiments__name__patch"];
        trace?: never;
    };
    "/api/v1/experiments/{name}/reports/{report_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_experiments__name__reports__report_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_v1_experiments__name__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/samples/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Sample */
        get: operations["download_sample_api_v1_experiments__name__samples__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/samples.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Samples Zip */
        get: operations["download_samples_zip_api_v1_experiments__name__samples_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_api_v1_experiments__name__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Audit */
        get: operations["get_experiment_audit_api_v1_experiments__name__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_api_v1_experiments__name__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/deletion-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deletion Summary
         * @description Реальные числа для модалки подтверждения удаления (FRONTEND.md §5.2:
         *     "Будут удалены: назначения (N), датасеты (M), результаты (K)") — то же
         *     самое, что abkit.jobs.run_delete_experiment пишет в audit_log, но здесь
         *     только для превью, без самого удаления.
         */
        get: operations["get_deletion_summary_api_v1_experiments__name__deletion_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blocks */
        get: operations["get_blocks_api_v1_experiments__name__blocks_get"];
        /** Put Blocks */
        put: operations["put_blocks_api_v1_experiments__name__blocks_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analyze */
        post: operations["start_analyze_api_v1_experiments__name__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/analyze/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analyze Demo */
        post: operations["start_analyze_demo_api_v1_experiments__name__analyze_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{name}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Validate */
        post: operations["start_validate_api_v1_experiments__name__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Dataset */
        get: operations["preview_dataset_api_v1_datasets__dataset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/demo-design": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Demo Design Dataset
         * @description Визард дизайна, шаг "Данные" -> кнопка "Демо-данные" (FRONTEND.md
         *     §5.2) — то же самое, что app.py::render_design_tab делает при клике
         *     "Загрузить демо-данные": generate_demo_design_data + make_demo_design_config,
         *     только тут данные сразу сохраняются как pre_design датасет (визарду нужен
         *     dataset_id, не сырой DataFrame в сессии — состояние визарда живет на
         *     фронте, не в серверной сессии).
         */
        post: operations["create_demo_design_dataset_api_v1_datasets_demo_design_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/metric-baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Metric Baseline
         * @description Визард дизайна, шаг "Параметры", режим "абсолютный MDE" — live-пересчет
         *     в относительный MDE через baseline (среднее) метрики (FRONTEND.md §5.2).
         *     Читает ПОЛНЫЙ файл датасета (не urlPreview, который ограничен 500
         *     строками) — baseline должен быть точным, не оценкой по сэмплу.
         */
        post: operations["get_metric_baseline_api_v1_datasets__dataset_id__metric_baseline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_admin_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Design */
        post: operations["start_design_api_v1_design_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeDemoRequest */
        AnalyzeDemoRequest: {
            /**
             * Effect
             * @default 0.03
             */
            effect: number;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * Correction
             * @default holm
             */
            correction: string;
            /**
             * Compare Methods
             * @default false
             */
            compare_methods: boolean;
            /** Date Col */
            date_col?: string | null;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** User Email */
            user_email: string | null;
            /** Action */
            action: string;
            /** Object Type */
            object_type: string | null;
            /** Object Id */
            object_id: string | null;
            /** Object Name */
            object_name: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            } | null;
        };
        /** BlockIn */
        BlockIn: {
            /** Id */
            id?: string | null;
            /**
             * Kind
             * @default custom
             */
            kind: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content Md
             * @default
             */
            content_md: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /** BlockOut */
        BlockOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Content Md */
            content_md: string;
            /** Position */
            position: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Body_upload_dataset_api_v1_datasets_post */
        Body_upload_dataset_api_v1_datasets_post: {
            /** Kind */
            kind: string;
            /** Experiment Name */
            experiment_name?: string | null;
            /** File */
            file: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Password */
            password?: string | null;
        };
        /** CreateUserResponse */
        CreateUserResponse: {
            user: components["schemas"]["UserAdminOut"];
            /** Generated Password */
            generated_password: string;
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string | null;
            /** Experiment Name */
            experiment_name: string | null;
            /** Kind */
            kind: string;
            /** Filename */
            filename: string;
            /** N Rows */
            n_rows: number;
            /** Columns */
            columns: string[];
            /** Dtypes */
            dtypes?: {
                [key: string]: string;
            } | null;
            /** Uploaded By Email */
            uploaded_by_email: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** DatasetPreview */
        DatasetPreview: {
            /** Filename */
            filename: string;
            /** N Rows */
            n_rows: number;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** DeleteExperimentRequest */
        DeleteExperimentRequest: {
            /** Confirm */
            confirm: string;
        };
        /** DeletionSummary */
        DeletionSummary: {
            /** Assignments */
            assignments: number;
            /** Datasets */
            datasets: number;
            /** Results */
            results: number;
        };
        /** DemoDesignDatasetResponse */
        DemoDesignDatasetResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Suggested Config */
            suggested_config: {
                [key: string]: unknown;
            };
        };
        /**
         * DesignConfig
         * @description Полный конфиг дизайна эксперимента.
         */
        DesignConfig: {
            /** Name */
            name: string;
            /** Unit Col */
            unit_col: string;
            /** Groups */
            groups: {
                [key: string]: number;
            };
            /** Metrics */
            metrics: components["schemas"]["MetricConfig"][];
            /**
             * Alpha
             * @default 0.05
             */
            alpha: number;
            /**
             * Power
             * @default 0.8
             */
            power: number;
            /** Mde */
            mde?: number | null;
            /** Mde Abs Input */
            mde_abs_input?: number | null;
            /** Mde Source Metric */
            mde_source_metric?: string | null;
            /** Sample Size */
            sample_size?: number | null;
            /**
             * Split Method
             * @default stratified
             * @enum {string}
             */
            split_method: "simple" | "stratified" | "hash";
            /** Strata */
            strata?: string[];
            /**
             * N Buckets Continuous
             * @default 4
             */
            n_buckets_continuous: number;
            /**
             * Min Stratum Size
             * @default 20
             */
            min_stratum_size: number;
            /**
             * Nan Strategy
             * @default separate_stratum
             * @enum {string}
             */
            nan_strategy: "separate_stratum" | "drop" | "error";
            /** Hash Salt */
            hash_salt?: string | null;
            /**
             * Isolation
             * @default exclude
             * @enum {string}
             */
            isolation: "exclude" | "warn" | "off" | "exclude_selected";
            /**
             * Exclude Experiments
             * @default all_active
             */
            exclude_experiments: "all_active" | string[];
            /** Isolation Selected Experiments */
            isolation_selected_experiments?: string[];
            /** Seed */
            seed?: number | null;
            /** Computed */
            computed?: {
                [key: string]: unknown;
            } | null;
        };
        /** DesignRequest */
        DesignRequest: {
            config: components["schemas"]["DesignConfig"];
            /** Dataset Id */
            dataset_id: string;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Publication Status */
            publication_status: string;
            /** Owner Email */
            owner_email: string | null;
            /** Owner Name */
            owner_name: string | null;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Design Summary */
            design_summary: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Archived At */
            archived_at: string | null;
            /** Available Reports */
            available_reports: string[];
            /** Files */
            files: components["schemas"]["FileInfo"][];
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Publication Status */
            publication_status: string;
            /** Owner Email */
            owner_email: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Archived At */
            archived_at: string | null;
        };
        /** FileInfo */
        FileInfo: {
            /** Path */
            path: string;
            /** Size Kb */
            size_kb: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            progress: components["schemas"]["JobProgress"] | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** JobProgress */
        JobProgress: {
            /** Stage */
            stage?: string | null;
            /** Pct */
            pct?: number | null;
            /** Message */
            message?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MetricBaselineRequest
         * @description Форма метрики (как MetricConfig) для расчета baseline-среднего —
         *     нужен визарду дизайна (FRONTEND.md §5.2, шаг 3: live-пересчет абсолютного
         *     MDE в относительный).
         */
        MetricBaselineRequest: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Pre Col */
            pre_col?: string | null;
            /** Num */
            num?: string | null;
            /** Den */
            den?: string | null;
        };
        /** MetricBaselineResponse */
        MetricBaselineResponse: {
            /** Baseline Mean */
            baseline_mean: number | null;
        };
        /**
         * MetricConfig
         * @description Описание одной метрики эксперимента.
         */
        MetricConfig: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "continuous" | "binary" | "ratio";
            /**
             * Role
             * @default primary
             * @enum {string}
             */
            role: "primary" | "secondary";
            /** Pre Col */
            pre_col?: string | null;
            /** Num */
            num?: string | null;
            /** Den */
            den?: string | null;
            /** Default Methods */
            default_methods?: string[] | null;
        };
        /** PaginatedAudit */
        PaginatedAudit: {
            /** Items */
            items: components["schemas"]["AuditEntryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaginatedDatasets */
        PaginatedDatasets: {
            /** Items */
            items: components["schemas"]["DatasetOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaginatedExperiments */
        PaginatedExperiments: {
            /** Items */
            items: components["schemas"]["ExperimentSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PatchExperimentRequest */
        PatchExperimentRequest: {
            /** Publication Status */
            publication_status?: string | null;
            /** Name */
            name?: string | null;
        };
        /** PatchUserRequest */
        PatchUserRequest: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ResetPasswordResponse */
        ResetPasswordResponse: {
            /** New Password */
            new_password: string;
        };
        /** SampleInfo */
        SampleInfo: {
            /** Filename */
            filename: string;
            /** N Rows */
            n_rows: number;
            /** Size Kb */
            size_kb: number;
        };
        /** StatusChangeRequest */
        StatusChangeRequest: {
            /** To */
            to: string;
        };
        /** UserAdminOut */
        UserAdminOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * N Sims
             * @default 2000
             */
            n_sims: number;
            /**
             * Compare Methods
             * @default false
             */
            compare_methods: boolean;
            /**
             * Effect
             * @default 0.05
             */
            effect: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: {
                status?: string | null;
                owner?: string | null;
                pub?: string | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExperiments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_v1_experiments__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experiment_api_v1_experiments__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_experiment_api_v1_experiments__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_experiments__name__reports__report_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_name: string;
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_v1_experiments__name__samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_sample_api_v1_experiments__name__samples__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                filename: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_samples_zip_api_v1_experiments__name__samples_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_api_v1_experiments__name__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_audit_api_v1_experiments__name__audit_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAudit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_experiments__name__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deletion_summary_api_v1_experiments__name__deletion_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blocks_api_v1_experiments__name__blocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_blocks_api_v1_experiments__name__blocks_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analyze_api_v1_experiments__name__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analyze_demo_api_v1_experiments__name__analyze_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeDemoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_validate_api_v1_experiments__name__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDatasets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_dataset_api_v1_datasets__dataset_id__preview_get: {
        parameters: {
            query?: {
                rows?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_design_dataset_api_v1_datasets_demo_design_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoDesignDatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_baseline_api_v1_datasets__dataset_id__metric_baseline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricBaselineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricBaselineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_admin_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                user?: string | null;
                action?: string | null;
                object_name?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAudit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_design_api_v1_design_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                abkit_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
}
